-- user/plugins/mason-null-ls.lua

-- return {
--   "jay-babu/mason-null-ls.nvim",
--   event = { "BufReadPre", "BufNewFile" },
--   dependencies = {
--     "williamboman/mason.nvim",
--     "jose-elias-alvarez/null-ls.nvim",
--   },
--   config = function()
--     require("mason-null-ls").setup({
--       ensure_installed = { "black", "ruff" },
--     })
--     local null_ls = require("null-ls")
--     null_ls.setup({
--       sources = {
--         -- Python
--         null_ls.builtins.formatting.black.with({
--           extra_args = { "--line-length=120" },
--         }),
--         null_ls.builtins.diagnostics.ruff,
--         -- JavaScript, TypeScript
--         null_ls.builtins.formatting.prettier,
--         -- Lua
--         null_ls.builtins.formatting.stylua,
--         null_ls.builtins.completion.luasnip,
--         null_ls.builtins.diagnostics.luacheck,
--         -- Refactoring for Go, Javascript, Lua, Python, TypeScript
--         null_ls.builtins.code_actions.refactoring,
--       },
--     })
--   end,
-- }
